# Generated by Django 4.0.2 on 2022-02-03 16:00

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='balance',
            field=models.PositiveIntegerField(validators=[webapp.validators.MinValueValidator(5)], verbose_name='остаток'),
        ),
    ]
