# Generated by Django 4.0.2 on 2022-02-03 16:01

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[webapp.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
