# Generated by Django 4.0.2 on 2022-02-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_productbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasket',
            name='volume',
            field=models.PositiveIntegerField(),
        ),
    ]
