# Generated by Django 4.0.2 on 2022-02-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_productbasket_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_basket', to='webapp.product', verbose_name='Корзина'),
        ),
    ]
