# Generated by Django 4.0.2 on 2022-02-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
