# Generated by Django 4.0.2 on 2022-03-04 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0015_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbasket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_basket', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
