# Generated by Django 4.0.2 on 2022-03-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_productbasket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbasket',
            name='user',
        ),
    ]
