# Generated by Django 4.0.2 on 2022-03-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_productbasket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbasket',
            name='session',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
